// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile(arg1:number):Promise<void>;

export function Greet(arg1:string):Promise<string>;
